[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "drafty-pipeline"
version = "0.0.0"
description = "Data pipeline"
dependencies = [
  "astroid>=3.3.1",
  "cappa>=0.22.4",
  "more-itertools>=10.4.0",
  "pydantic>=2.9.1",
]
[project.scripts]
"drafty-pipeline" = "drafty_pipeline.__main__:main"

[tool.fawltydeps]
deps = ["packages/_pipeline/pyproject.toml"]
code = ["packages/_pipeline/src"]
ignore_undeclared = [
  "drafty_dev",
  "drafty_pipeline",
  "cachier",
  "context_models",
  "pipeline_helper",
]
