# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.2.0-48-g59db0e7
_src_path: gh:softboiler/copier-pipeline
actions_runner: ubuntu-24.04
github_repo_name: blue-prince
package_name: blue_prince
project_description: Tools for solving the mysteries and puzzles of Blue Prince
project_email: blake.naccarato@gmail.com
project_name: blue-prince
project_owner_github_username: Blake Naccarato
project_owner_name: Blake Naccarato
project_version: 0.0.0
python_version: '3.11'
year_of_project_creation: 2025
