# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2025.1.3-27-g39d3a15
_src_path: gh:softboiler/copier-pipeline
actions_runner: ubuntu-24.04
github_repo_name: drafty
package_name: drafty
project_description: Blue Prince drafting assistant
project_email: blake.naccarato@gmail.com
project_name: drafty
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 0.0.0
publish_project: true
python_version: '3.11'
year_of_project_creation: 2025
